/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface StakeTransfererInterface extends ethers.utils.Interface {
  functions: {
    "receiversWhitelist(address)": FunctionFragment;
    "setReceiverWhitelisted(address,bool)": FunctionFragment;
    "exitAndTransfer(address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "receiversWhitelist",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "setReceiverWhitelisted",
    values: [string, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "exitAndTransfer",
    values: [string]
  ): string;

  decodeFunctionResult(
    functionFragment: "receiversWhitelist",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setReceiverWhitelisted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "exitAndTransfer",
    data: BytesLike
  ): Result;

  events: {};
}

export class StakeTransferer extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: StakeTransfererInterface;

  functions: {
    receiversWhitelist(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    "receiversWhitelist(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    setReceiverWhitelisted(
      receiver: string,
      whitelisted: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "setReceiverWhitelisted(address,bool)"(
      receiver: string,
      whitelisted: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    exitAndTransfer(
      transferTo: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "exitAndTransfer(address)"(
      transferTo: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  receiversWhitelist(arg0: string, overrides?: CallOverrides): Promise<boolean>;

  "receiversWhitelist(address)"(
    arg0: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  setReceiverWhitelisted(
    receiver: string,
    whitelisted: boolean,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "setReceiverWhitelisted(address,bool)"(
    receiver: string,
    whitelisted: boolean,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  exitAndTransfer(
    transferTo: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "exitAndTransfer(address)"(
    transferTo: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    receiversWhitelist(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    "receiversWhitelist(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    setReceiverWhitelisted(
      receiver: string,
      whitelisted: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    "setReceiverWhitelisted(address,bool)"(
      receiver: string,
      whitelisted: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    exitAndTransfer(
      transferTo: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "exitAndTransfer(address)"(
      transferTo: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    receiversWhitelist(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "receiversWhitelist(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    setReceiverWhitelisted(
      receiver: string,
      whitelisted: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "setReceiverWhitelisted(address,bool)"(
      receiver: string,
      whitelisted: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    exitAndTransfer(
      transferTo: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "exitAndTransfer(address)"(
      transferTo: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    receiversWhitelist(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "receiversWhitelist(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    setReceiverWhitelisted(
      receiver: string,
      whitelisted: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "setReceiverWhitelisted(address,bool)"(
      receiver: string,
      whitelisted: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    exitAndTransfer(
      transferTo: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "exitAndTransfer(address)"(
      transferTo: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
