/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { IStakeTransferer } from "../IStakeTransferer";

export class IStakeTransferer__factory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IStakeTransferer {
    return new Contract(address, _abi, signerOrProvider) as IStakeTransferer;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "receiver",
        type: "address",
      },
      {
        internalType: "bool",
        name: "whitelisted",
        type: "bool",
      },
    ],
    name: "setReceiverWhitelisted",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];
