/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { PercentageCalculator } from "../PercentageCalculator";

export class PercentageCalculator__factory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): PercentageCalculator {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as PercentageCalculator;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_amount",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_percentage",
        type: "uint256",
      },
    ],
    name: "percentageCalc",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
];
