/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { RewardsDistributionRecipient } from "../RewardsDistributionRecipient";

export class RewardsDistributionRecipient__factory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): RewardsDistributionRecipient {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as RewardsDistributionRecipient;
  }
}

const _abi = [
  {
    inputs: [],
    name: "rewardsDistributor",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "start",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];
