/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { StakeLock } from "../StakeLock";

export class StakeLock__factory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): StakeLock {
    return new Contract(address, _abi, signerOrProvider) as StakeLock;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_lockEndBlock",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [],
    name: "lockEndBlock",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];
