/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { StakeReceiver } from "../StakeReceiver";

export class StakeReceiver__factory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): StakeReceiver {
    return new Contract(address, _abi, signerOrProvider) as StakeReceiver;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "staker",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "stake",
        type: "uint256",
      },
    ],
    name: "delegateStake",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];
